name: Compile and Distribute Helm Charts

on:
  schedule:
    - cron: '* 4 * * *'
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Checkout Openstack-Helm-Infra @ Specific Version
        uses: actions/checkout@v2
        with:
          repository: 'openstack/openstack-helm-infra'
          ref: 'master'
          path: 'openstack-helm-infra'
      - name: Remove openstack-helm-infra git references
        run: rm -rf openstack-helm-infra/.git
      - name: Replace all instances of "http://localhost:8879/charts" with "https://registry.thecore.net.au/chartrepo/openstack"
        run: find . -type f -name 'requirements.yaml' -exec sed -i 's/http\:\/\/localhost\:8879\/charts/https\:\/\/registry\.thecore\.net\.au\/chartrepo\/openstack/g' {} \;
      - name: Show repo output
        run: ls -lah
      - name: Remove prometheus-kube-state-metrics as it is invalid
        run: rm -rf openstack-helm-infra/prometheus-kube-state-metrics
      - name: Install Helm Push Plugin
        run: helm plugin install https://github.com/chartmuseum/helm-push.git
      - name: Push helm-toolkit chart first
        run: cd openstack-helm-infra && make package helm-toolkit && helm push *.tgz https://registry.thecore.net.au/chartrepo/openstack
        env:
          HELM_REPO_USERNAME: ${{ secrets.HARBOR_ROBOT }}
          HELM_REPO_PASSWORD: ${{ secrets.HARBOR_ROBOT_TOKEN }}
      - name: Package each of the Openstack-Helm-Infra charts
        run: cd openstack-helm-infra && make package all
      - name: Push each of the Openstack-Helm-Infra charts to Registry
        run: find openstack-helm-infra -type f -name '*.tgz' -exec helm push {} https://registry.thecore.net.au/chartrepo/openstack \;
        env:
          HELM_REPO_USERNAME: ${{ secrets.HARBOR_ROBOT }}
          HELM_REPO_PASSWORD: ${{ secrets.HARBOR_ROBOT_TOKEN }}

      ###
      # Openstack-Helm-Charts
      ###
      - name: Checkout Openstack-Helm @ Specific Version
        uses: actions/checkout@v2
        with:
          repository: 'openstack/openstack-helm'
          ref: 'b65988fa5cd08142facb7709e524d417d2ff9a66'
          path: 'openstack-helm'
      - name: Remove openstack-helm git references
        run: rm -rf openstack-helm/.git
      - name: Replace all instances of "http://localhost:8879/charts" with "https://registry.thecore.net.au/chartrepo/openstack"
        run: find . -type f -name 'requirements.yaml' -exec sed -i 's/http\:\/\/localhost\:8879\/charts/https\:\/\/registry\.thecore\.net\.au\/chartrepo\/openstack/g' {} \;
      - name: Show repo output
        run: ls -lah openstack-helm
      - name: Package each of the Openstack-Helm charts
        run: cd openstack-helm && make package all
      - name: Push each of the Openstack-Helm charts to Registry
        run: find openstack-helm -type f -name '*.tgz' -exec helm push {} https://registry.thecore.net.au/chartrepo/openstack \;
        env:
          HELM_REPO_USERNAME: ${{ secrets.HARBOR_ROBOT }}
          HELM_REPO_PASSWORD: ${{ secrets.HARBOR_ROBOT_TOKEN }}
