name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Checkout Openstack-Helm @ Specific Version
        uses: actions/checkout@v2
        with:
          repository: 'openstack/openstack-helm'
          ref: 'afd68753c720094e61fee24f001a2d826f1929ae'
          path: 'charts'
      - name: Remove openstack-helm git references
        run: rm -rf charts/.git
      - name: Show repo output
        run: ls -lah
      - name: Launch Local Helm Server 
        run: helm serve --repo-path ./charts
      - name: Make all charts
        run: cd charts && make all
