name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Openstack-Helm @ Master
        uses: actions/checkout@v2
        with:
          repository: 'openstack/openstack-helm'
          ref: 'master'
          path: 'charts'
      - name: Show repo output
        run: ls -lah
      - name: Execute Chart Releaser
        using: 'docker'
        image: 'helmpack/chart-releaser:latest'
